##Spring Configuration
server:
  port: 8080
spring:
  application:
    name: ms_reportes_crediya
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: /h2
  profiles:
    include:
